apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-challenge
  labels:
    app: mysql
type: Opaque
stringData:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: db
  DB_USERNAME: user
  MYSQL_PASSWORD: 9832nriu4b43gb
  MYSQL_ROOT_PASSWORD: i32ubbiub43i2b324h
