apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  # Base64 encoded values
  # MYSQL_ROOT_PASSWORD: i32ubbiub43i2b324h (encoded: aTMydWJiaXViNDNpMmIzMjRo)
  # MYSQL_PASSWORD: 9832nriu4b43gb (encoded: OTgzMm5yaXU0YjQzZ2I=)
  MYSQL_ROOT_PASSWORD: aTMydWJiaXViNDNpMmIzMjRo
  MYSQL_PASSWORD: OTgzMm5yaXU0YjQzZ2I=
